Repository boostcampwm-2022/web07-zokboo.com, pull requests merged in 2022-11, with the labels that each got.

#7 [Chore] Add pre-commit hook
  .gitignore
  .husky/pre-commit
  package-lock.json
  package.json
Labels: chore

#8 [DOCS] readme 목표, 개요, 팀원 추가
  README.md
Labels: 리뷰 X, docs

#10 [INIT] React 셋업
  README.md
  client/.eslintrc.js
  client/.gitignore
  client/.prettierrc
  client/README.md
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.test.tsx
  client/src/App.tsx
  client/src/index.tsx
  client/src/react-app-env.d.ts
  client/src/reportWebVitals.ts
  client/src/setupTests.ts
  client/tsconfig.json
Labels: init, frontend

#12 [INIT] React Package 셋업
  client/package-lock.json
  client/package.json
Labels: init, frontend

#21 [FIX] 프론트엔드 eslint 루트에 설치
  package-lock.json
  package.json
Labels: fix, init, frontend

#22 [INIT] React Router 셋업
  client/README.md
  client/src/App.tsx
  client/src/pages/Exam.tsx
  client/src/pages/ExamCreate.tsx
  client/src/pages/FindId.tsx
  client/src/pages/FindPw.tsx
  client/src/pages/Home.tsx
  client/src/pages/Login.tsx
  client/src/pages/MyPage.tsx
  client/src/pages/Problem.tsx
  client/src/pages/ProblemCreate.tsx
  client/src/pages/Review.tsx
  client/src/pages/Search.tsx
  client/src/pages/SignUp.tsx
  client/src/router/Router.tsx
Labels: init, frontend

#26 [INIT] React style Theme Setup
  client/src/styles/theme.ts
Labels: init, frontend

#27 [DESIGN] Common Component Logo & DashBoard
  client/src/assets/images/add.svg
  client/src/components/common/Logo.tsx
  client/src/components/dashboard/DashBoard.tsx
  client/src/components/dashboard/DashBoardItem.tsx
Labels: frontend, design

#36 [Chore] Add passport related packages
  server/package-lock.json
  server/package.json
  server/src/AppModule.ts
  server/src/app.controller.spec.ts
  server/src/app.controller.ts
  server/src/app.module.ts
  server/src/app.service.ts
  server/src/main.ts
  server/src/modules/auth/AuthModule.ts
  server/src/modules/auth/index.ts
  server/test/app.e2e-spec.ts
Labels: refactor, chore, backend, 리뷰요청

#39 init:global style setup
  client/src/assets/images/add.svg
  client/src/components/common/Logo.tsx
  client/src/components/dashboard/DashBoard.tsx
  client/src/components/dashboard/DashBoardItem.tsx
  client/src/router/Router.tsx
  client/src/styles/Global.tsx
Labels: init, frontend

#13 [DOCS] Add issue template
  .github/ISSUE_TEMPLATE/backend-feature-request.md
  .github/ISSUE_TEMPLATE/backlog.md
  .github/ISSUE_TEMPLATE/configuration.md
  .github/ISSUE_TEMPLATE/frontend-feature-request.md
Labels: 리뷰 X, docs

#40 Prisma 기본 설정
  .gitignore
  .husky/pre-commit
  server/.env.example
  server/.prettierrc
  server/package-lock.json
  server/package.json
  server/prisma/schema.prisma
  server/src/modules/common/CommonModule.ts
  server/src/modules/common/PrismaInstance.ts
  server/test/app.e2e-spec.ts
Labels: chore, backend

#41 [design] common component 작업 (버튼, 드롭다운)
  client/package-lock.json
  client/src/components/CommonButtonComponent.tsx
  client/src/components/CommonDropdown.tsx
  client/src/components/CommonDropdownContainer.tsx
  client/src/images/dropdown-arrow.svg
  client/src/pages/Main.tsx
Labels: feat, frontend, design

#43 [INIT] Update Theme
  client/src/styles/theme.ts
Labels: frontend, design

#48 [DESIGN] Theme Apply
  client/src/components/dashboard/DashBoard.tsx
  client/src/components/header/Header.tsx
  client/src/pages/Home.tsx
Labels: frontend, design

#49 style : common component name 변경
  client/src/components/common/Button.tsx
  client/src/components/common/Dropdown.tsx
  client/src/components/common/DropdownContainer.tsx
Labels: style

#44 design : 로그인 화면 레이아웃 구성
  client/src/assets/images/github-icon.png
  client/src/assets/images/google-icon.png
  client/src/assets/images/kakao-icon.png
  client/src/assets/images/naver-icon.png
  client/src/pages/Login.tsx
Labels: frontend, design

#50 [DESIGN] Update Theme
  client/src/components/header/Header.tsx
  client/src/pages/Home.tsx
  client/src/styles/theme.ts
Labels: frontend, design

#52 [DESIGN] Main Layout Renewer
  client/package-lock.json
  client/package.json
  client/src/components/chart/Chart.tsx
  client/src/components/common/Toggle.tsx
  client/src/components/dashboard/DashBoard.tsx
  client/src/hooks/useArrayValue.tsx
  client/src/hooks/useToggleValue.tsx
  client/src/pages/Home.tsx
Labels: feat, frontend, design

#53 [FEAT] 로컬 회원가입 기능 및 카카오 SSO 기능 구현
  server/.env.example
  server/.gitattributes
  server/package-lock.json
  server/package.json
  server/prisma/schema.prisma
  server/src/AppModule.ts
  server/src/GlobalExceptionFilter.ts
  server/src/main.ts
  server/src/modules/auth/AuthController.ts
  server/src/modules/auth/AuthModule.ts
  server/src/modules/auth/AuthRepository.ts
  server/src/modules/auth/AuthService.ts
  server/src/modules/auth/index.ts
  server/src/modules/auth/strategies/JwtStrategy.ts
  server/src/modules/auth/strategies/KakaoStrategy.ts
  server/src/modules/auth/strategies/index.ts
  server/src/modules/common/exception/CustomError.ts
  server/src/modules/common/exception/ErrorResponse.ts
  server/src/modules/common/exception/ErrorUtils.ts
  server/src/modules/common/response/ApiResponse.ts
  server/src/modules/user/UserModule.ts
  server/src/modules/user/UserRepository.ts
  server/src/modules/user/UserService.ts
  server/src/modules/user/domain/BasicUser.ts
  server/src/modules/user/domain/OauthUser.ts
  server/src/modules/user/domain/User.ts
  server/src/modules/user/dto/request/SSOSignupRequest.ts
  server/src/modules/user/dto/request/SignupRequest.ts
  server/src/modules/user/dto/response/SignupResponse.ts
  server/src/modules/user/enum/OauthType.ts
Labels: feat, backend, 리뷰요청

#63 [REFACTOR] Common Components
  client/src/assets/images/logo.png
  client/src/assets/images/search.png
  client/src/components/common/Button.tsx
  client/src/components/common/Logo.tsx
  client/src/components/common/Toggle.tsx
  client/src/components/header/Header.tsx
  client/src/pages/Home.tsx
  client/src/pages/Login.tsx
  client/src/pages/ProblemCreate.tsx
  client/src/pages/home/Home.tsx
  client/src/pages/home/Style.tsx
  client/src/router/Router.tsx
  client/src/styles/Global.tsx
Labels: refactor, frontend, design

#55 Local Login 구현
  server/package-lock.json
  server/package.json
  server/src/GlobalExceptionFilter.ts
  server/src/main.ts
  server/src/modules/auth/AuthController.ts
  server/src/modules/auth/AuthModule.ts
  server/src/modules/auth/AuthService.ts
  server/src/modules/auth/guard/jwtAuthGuard.ts
  server/src/modules/auth/strategies/JwtStrategy.ts
  server/src/modules/user/UserModule.ts
  server/src/modules/user/UserRepository.ts
  server/src/modules/user/domain/BasicUser.ts
  server/src/modules/user/domain/User.ts
  server/src/modules/user/dto/request/SigninRequest.ts
  server/src/modules/user/dto/response/SigninResponse.ts
Labels: feat, backend, 리뷰요청

#58 feat: msw설치 및 mock data 적용
  client/package-lock.json
  client/package.json
  client/src/components/search/SearchResultItem.tsx
  client/src/mocks/handlers.ts
  client/src/mocks/researchMockData.ts
  client/src/mocks/worker.ts
  client/src/pages/Login.tsx
  client/src/pages/Search.tsx
Labels: frontend, 리뷰요청

#61 [FIX] fix kakao signup
  server/@types/express/index.d.ts
  server/src/modules/auth/AuthController.ts
Labels: fix, backend

#66 [DESIGN] Header 디자인 수정
  client/src/components/header/Header.tsx
  client/src/components/header/Style.tsx
  client/src/pages/home/Style.tsx
Labels: frontend, design

#67 [FEAT] Swagger 작업 진행
  server/package-lock.json
  server/package.json
  server/src/main.ts
Labels: feat, backend

#68 구글 SSO 구현
  server/@types/express/index.d.ts
  server/package-lock.json
  server/package.json
  server/prisma/schema.prisma
  server/src/modules/auth/AuthController.ts
  server/src/modules/auth/AuthModule.ts
  server/src/modules/auth/AuthRepository.ts
  server/src/modules/auth/AuthService.ts
  server/src/modules/auth/strategies/GoogleStrategy.ts
  server/src/modules/user/UserRepository.ts
  server/src/modules/user/UserService.ts
  server/src/modules/user/domain/OauthUser.ts
  server/src/modules/user/dto/request/SSOSigninRequest.ts
  server/src/modules/user/dto/request/SSOSignupRequest.ts
Labels: feat, backend, 리뷰요청

#69 [FEAT] Naver SSO 작업
  server/.env.example
  server/src/modules/auth/AuthController.ts
  server/src/modules/auth/AuthModule.ts
  server/src/modules/auth/strategies/NaverStrategy.ts
  server/src/modules/auth/strategies/index.ts
Labels: feat, backend

#64 refactor : common dropdown 변경
  client/src/components/common/Dropdown.tsx
  client/src/components/common/DropdownContainer.tsx
Labels: refactor

#70 feat: 깃헙 SSO 구현 및 Oauth 마무리
  server/src/modules/auth/AuthController.ts
  server/src/modules/auth/AuthModule.ts
  server/src/modules/auth/AuthRepository.ts
  server/src/modules/auth/AuthService.ts
  server/src/modules/auth/index.ts
  server/src/modules/auth/strategies/GithubStrategy.ts
  server/src/modules/common/exception/CustomError.ts
  server/src/modules/common/exception/ErrorResponse.ts
  server/src/modules/common/exception/ErrorUtils.ts
  server/src/modules/user/UserService.ts
  server/src/modules/user/dto/request/SignupRequest.ts
Labels: feat, backend, 리뷰요청

#74 [INIT] React Query Setup
  client/package-lock.json
  client/package.json
  client/src/index.tsx
  client/src/react-query/queries/temp
Labels: 👋 init, 🧩 frontend

#75 [INIT] msw
  client/package.json
  client/public/mockServiceWorker.js
  client/src/index.tsx
  client/src/mocks/data/problem/index.ts
  client/src/mocks/handlers.ts
  client/src/mocks/handlers/index.ts
  client/src/mocks/handlers/problem/index.ts
  client/src/mocks/worker.ts
Labels: 👋 init, 🧩 frontend

#76 [FEAT] Question 도메인 도메인 클래스 및 레포지토리 생성, 조회 쿼리 구현
  server/prisma/schema.prisma
  server/src/modules/question/QuestionModule.ts
  server/src/modules/question/QuestionRepository.ts
  server/src/modules/question/domain/Hashtag.ts
  server/src/modules/question/domain/Option.ts
  server/src/modules/question/domain/Question.ts
  server/src/modules/question/domain/QuestionImage.ts
  server/src/modules/question/enum/QuestionType.ts
  server/src/modules/user/enum/OauthType.ts
Labels: 💻 feat, ⚙️ backend, 🙋 리뷰요청

#79 [refecor] common dropdown 방식 변경
  client/src/components/common/Dropdown.tsx
  client/src/components/common/DropdownContainer.tsx
Labels: 🛠 refactor, 🧩 frontend

#85 [FEAT] develop 브랜치 cicd 파이프라인 구축
  .github/workflows/dev-cicd.yml
  server/Dockerfile
  server/src/main.ts
Labels: 💻 feat, 🙅 리뷰 X

#81 [DESIGN] Problem Create Modal
  client/src/components/modal/Style.tsx
  client/src/components/modal/create/Style.tsx
  client/src/components/modal/create/index.tsx
  client/src/components/modal/index.tsx
  client/src/components/modal/search/Style.tsx
  client/src/components/modal/search/index.tsx
  client/src/hooks/useToggle.tsx
  client/src/hooks/useToggleValue.tsx
  client/src/pages/problemCreate/ProblemCreate.tsx
  client/src/pages/problemCreate/Style.tsx
  client/src/styles/Global.tsx
  client/src/styles/theme.ts
Labels: 🧩 frontend, 🎨 design

#83 [FEAT] 메일 서비스 구현
  server/.env.example
  server/package-lock.json
  server/package.json
  server/prisma/schema.prisma
  server/src/modules/auth/AuthController.ts
  server/src/modules/auth/AuthService.ts
  server/src/modules/auth/dto/response/VerifyResponse.ts
  server/src/modules/common/CommonModule.ts
  server/src/modules/common/MailService.ts
  server/src/modules/user/UserRepository.ts
  server/src/modules/user/domain/BasicUser.ts
Labels: 💻 feat, ⚙️ backend

#88 기작업 된 API 스웨거 명세화
  server/prisma/migrations/20221123062559_/migration.sql
  server/prisma/migrations/migration_lock.toml
  server/src/decorators/ApiResponseDecorator.ts
  server/src/main.ts
  server/src/modules/auth/AuthController.ts
  server/src/modules/common/response/ApiResponse.ts
  server/src/modules/question/QuestionController.ts
  server/src/modules/question/dto/request/CreateQuestionRequest.ts
  server/src/modules/question/dto/response/CreateQuestionResponse.ts
  server/src/modules/user/dto/request/SigninRequest.ts
  server/src/modules/user/dto/request/SignupRequest.ts
  server/src/modules/user/dto/response/SigninResponse.ts
  server/src/modules/user/dto/response/SignupResponse.ts
Labels: ⚙️ backend, 🙋 리뷰요청, 📑 docs

#84 [DESIGN] 아이디찾기 / 비밀번호찾기 페이지 레이아웃 구현
  client/src/components/login/LoginModal.tsx
  client/src/pages/FindId.tsx
  client/src/pages/FindId/FindId.tsx
  client/src/pages/FindId/Style.tsx
  client/src/pages/FindPw.tsx
  client/src/pages/findPw/FindPw.tsx
  client/src/pages/findPw/Style.tsx
  client/src/router/Router.tsx
Labels: 🧩 frontend, 🎨 design

#87 [DESIGN] Search Problem 모달
  client/src/components/modal/Style.tsx
  client/src/components/modal/create/Style.tsx
  client/src/components/modal/search/Style.tsx
  client/src/components/modal/search/index.tsx
  client/src/pages/problemCreate/ProblemCreate.tsx
Labels: 🧩 frontend, 🎨 design

#91 [REFACTOR] Problem Create
  client/src/components/chart/Chart.tsx
  client/src/components/chart/Style.tsx
  client/src/components/common/Dropdown.tsx
  client/src/components/common/DropdownContainer.tsx
  client/src/components/common/dropdown/Dropdown.tsx
  client/src/components/common/dropdown/Style.tsx
  client/src/components/common/dropdown/Types.ts
  client/src/components/dashboard/DashBoard.tsx
  client/src/components/dashboard/Style.tsx
  client/src/components/header/Header.tsx
  client/src/components/header/Style.tsx
  client/src/components/modal/Style.tsx
  client/src/components/modal/create/Style.tsx
  client/src/components/modal/create/constants.ts
  client/src/components/modal/create/index.tsx
  client/src/hooks/useToggleValue.tsx
  client/src/pages/home/Home.tsx
  client/src/pages/home/Style.tsx
  client/src/pages/problemCreate/ProblemCreate.tsx
  client/src/pages/problemCreate/Style.tsx
  client/src/styles/Global.tsx
  client/src/styles/common.tsx
Labels: 🛠 refactor, 🧩 frontend, 🎨 design

#101 [HOTFIX] 폴더이름관련 에러 해결
  client/src/router/Router.tsx
Labels: 🔨 fix

#89 [DESIGN] 회원가입 페이지
  client/src/hooks/useInput.tsx
  client/src/pages/Login.tsx
  client/src/pages/SignUp.tsx
  client/src/pages/signup/SignUp.tsx
  client/src/pages/signup/Style.tsx
  client/src/router/Router.tsx
  client/src/styles/theme.ts
Labels: 💻 feat, 🧩 frontend, 🎨 design

#94 [FEAT] Create Problem MSW 작성
  client/.eslintrc.js
  client/src/api/question/index.ts
  client/src/components/modal/create/index.tsx
  client/src/index.tsx
  client/src/mocks/data/search/index.ts
  client/src/mocks/handlers/index.ts
  client/src/mocks/handlers/question/index.ts
  client/src/mocks/handlers/search/index.ts
  client/src/types/question/index.ts
Labels: 💻 feat, 🧩 frontend

#111 [FIX] frontend 배포환경 수정
  .github/workflows/frontend.yml
Labels: 🙅 리뷰 X

#112 [FIX] frontend cicd action 변경
  .github/workflows/frontend.yml
Labels: 👋 init, 🙅 리뷰 X

#113 [TEST] 회원가입 페이지에 대한 test 코드 작성
  client/src/App.test.tsx
  client/src/pages/signup/SignUp.test.tsx
  client/src/pages/signup/SignUp.tsx
  client/src/pages/signup/constants.ts
Labels: 🔎 test

#115 [FIX] frontend github action 개발 환경 우선 설정
  .github/workflows/front_dev.yml
  .github/workflows/front_prod.yml
Labels: 🔨 fix, 🙅 리뷰 X

#100 [FEAT] 문제 검색 API
  server/src/modules/question/QuestionController.ts
  server/src/modules/question/QuestionRepository.ts
  server/src/modules/question/QuestionService.ts
  server/src/modules/question/dto/query/GetQuestionsQuery.ts
  server/src/modules/question/dto/response/GetQuestionsResponse.ts
Labels: 💻 feat, ⚙️ backend, 🙋 리뷰요청

#103 [FEAT] Header Route
  client/src/components/header/Header.tsx
  client/src/components/header/Style.tsx
Labels: 💻 feat, 🧩 frontend

#109 [FEAT] 타인의 문제집 저장 API 작성
  server/src/modules/workbook/WorkbookController.ts
  server/src/modules/workbook/WorkbookRepository.ts
  server/src/modules/workbook/WorkbookService.ts
  server/src/modules/workbook/domain/Workbook.ts
  server/src/modules/workbook/domain/WorkbookLike.ts
  server/src/modules/workbook/dto/request/DuplicateWorkbookRequest.ts
Labels: 💻 feat, ⚙️ backend, 🙋 리뷰요청

#118 [FEAT] 문제집 상세 조회 API
  server/src/modules/workbook/WorkbookController.ts
  server/src/modules/workbook/WorkbookRepository.ts
  server/src/modules/workbook/WorkbookService.ts
  server/src/modules/workbook/domain/Workbook.ts
  server/src/modules/workbook/dto/request/DuplicateWorkbookRequest.ts
  server/src/modules/workbook/dto/response/QuestionDetailResponse.ts
  server/src/modules/workbook/dto/response/WorkbookDetailResponse.ts
Labels: 💻 feat, ⚙️ backend, 🙋 리뷰요청, 📑 docs

#124 [FEAT] 패스워드 재설정 API 구현
  server/.env.example
  server/src/modules/auth/AuthController.ts
  server/src/modules/auth/AuthService.ts
  server/src/modules/auth/dto/request/ResetPasswordRequest.ts
  server/src/modules/auth/dto/response/ResetPasswordResponse.ts
  server/src/modules/auth/dto/response/ResetTokenResponse.ts
  server/src/modules/common/MailService.ts
  server/src/modules/user/domain/BasicUser.ts
Labels: 💻 feat, ⚙️ backend, 🙋 리뷰요청

#121 [FEAT] Search Question Modal & Create WorkBook
  client/.eslintrc.js
  client/package-lock.json
  client/package.json
  client/src/api/question.ts
  client/src/api/question/index.ts
  client/src/api/workbook.ts
  client/src/components/chart/Chart.tsx
  client/src/components/common/Toggle.tsx
  client/src/components/common/dropdown/Dropdown.tsx
  client/src/components/common/dropdown/Style.tsx
  client/src/components/modal/create/index.tsx
  client/src/components/modal/index.tsx
  client/src/components/modal/search/Style.tsx
  client/src/components/modal/search/constants.ts
  client/src/components/modal/search/index.tsx
  client/src/hooks/useToggleValue.tsx
  client/src/index.tsx
  client/src/mocks/data/question.ts
  client/src/mocks/data/search.ts
  client/src/mocks/handlers/index.ts
  client/src/mocks/handlers/question.ts
  client/src/mocks/handlers/question/index.ts
  client/src/mocks/handlers/search.ts
  client/src/mocks/handlers/workbook.ts
  client/src/mocks/worker.ts
  client/src/pages/workBookCreate/Style.tsx
  client/src/pages/workBookCreate/WorkBookCreate.tsx
  client/src/react-query/keys/question.ts
  client/src/react-query/queries/temp
  client/src/router/Router.tsx
  client/src/types/question.ts
  client/src/types/workbook.ts
  client/src/utils/constants.ts
Labels: 💻 feat, 🧩 frontend, 🙋 리뷰요청

#129 [FIX] frontend cicd 동작 성공 및 브랜치 develop으로 변경
  .github/workflows/front_dev.yml
Labels: 🔨 fix, 👋 init

#131 [DESIGN] Mypage Payout
  client/package-lock.json
  client/package.json
  client/src/components/header/Style.tsx
  client/src/components/modal/create/constants.ts
  client/src/components/modal/create/index.tsx
  client/src/pages/MyPage.tsx
  client/src/pages/home/Style.tsx
  client/src/pages/mypage/MyPage.tsx
  client/src/pages/mypage/Style.tsx
  client/src/pages/mypage/constants.ts
  client/src/pages/workBookCreate/Style.tsx
  client/src/router/Router.tsx
  client/src/styles/theme.ts
Labels: 🧩 frontend, 🙋 리뷰요청, 🎨 design

#133 [REFACTOR] 반응형 수정
  client/src/components/chart/Style.tsx
  client/src/components/header/Style.tsx
Labels: 🛠 refactor, 🧩 frontend, 🎨 design

#122 [FEAT] 문제집 검색 API 구현
  server/prisma/migrations/20221128083843_/migration.sql
  server/prisma/migrations/20221128085659_/migration.sql
  server/prisma/schema.prisma
  server/src/decorators/ApiResponseDecorator.ts
  server/src/modules/auth/AuthController.ts
  server/src/modules/question/QuestionController.ts
  server/src/modules/workbook/WorkbookController.ts
  server/src/modules/workbook/WorkbookRepository.ts
  server/src/modules/workbook/WorkbookService.ts
  server/src/modules/workbook/dto/response/WorkbookSimpleResponse.ts
Labels: 💻 feat, 🛠 refactor, ⚙️ backend, 🙋 리뷰요청, 📑 docs

#141 [REFACTOR] React-Query Error
  client/src/App.tsx
  client/src/components/modal/create/index.tsx
  client/src/components/modal/search/index.tsx
  client/src/index.tsx
  client/src/mocks/handlers/question.ts
  client/src/react-query/queryClient.ts
  client/src/router/Router.tsx
Labels: 🛠 refactor, 🧩 frontend, 🙋 리뷰요청

#153 Feat/production cicd
  .github/workflows/prod-cicd.yml
  deploy/deploy-blue-green.sh
  deploy/docker-compose.blue.yml
  deploy/docker-compose.green.yml
  server/package.json
Labels: 💻 feat, 🪠 chore, 🙅 리뷰 X
