Repository boostcampwm-2022/web07-zokboo.com, pull requests merged in 2022-12, with the labels that each got.

#144 [REFECTOR] useInput 에서 MAX_LENGTH 관련 로직 삭제
  client/src/api/login.ts
  client/src/hooks/useInput.tsx
  client/src/pages/Login.tsx
  client/src/pages/login/Login.tsx
  client/src/pages/login/Style.tsx
  client/src/pages/signup/SignUp.tsx
  client/src/pages/signup/constants.ts
  client/src/router/Router.tsx
Labels: 🛠 refactor, 🧩 frontend

#145 [REFACTOR] useArrayValue
  client/src/components/chart/Chart.tsx
Labels: 🛠 refactor, 🧩 frontend

#146 [REFACTOR] workbook create
  client/src/components/common/Loading.tsx
  client/src/components/modal/create/constants.ts
  client/src/components/modal/create/index.tsx
  client/src/components/modal/search/index.tsx
  client/src/hooks/useArrayText.tsx
  client/src/mocks/handlers/question.ts
  client/src/mocks/handlers/workbook.ts
  client/src/pages/workBookCreate/WorkBookCreate.tsx
Labels: 💻 feat, 🛠 refactor, 🧩 frontend

#155 [FEAT] 시험 제작 API 구현
  server/package-lock.json
  server/package.json
  server/src/AppModule.ts
  server/src/modules/common/response/ApiResponse.ts
  server/src/modules/test/TestController.ts
  server/src/modules/test/TestModule.ts
  server/src/modules/test/TestRepository.ts
  server/src/modules/test/TestService.ts
  server/src/modules/test/domain/Test.ts
  server/src/modules/test/domain/WorkbookTest.ts
  server/src/modules/test/dto/request/CreateTestRequest.ts
  server/src/modules/test/dto/request/CreateWorkbookTestRequest.ts
  server/src/modules/test/dto/response/TestSimpleResponse.ts
  server/src/modules/test/dto/response/WorkbookTestSimpleResponse.ts
  server/src/modules/workbook/WorkbookModule.ts
  server/src/modules/workbook/WorkbookRepository.ts
  server/src/modules/workbook/domain/WorkbookQuestion.ts
Labels: 💻 feat, ⚙️ backend, 🙋 리뷰요청, 📑 docs

#149 [DESIGN] MyPage 의 나의 문제집 및 공유받은 문제집 컴포넌트 추가
  client/src/components/mypage/Workbook.tsx
  client/src/components/search/SearchResultItem.tsx
  client/src/components/workbookItem/Style.tsx
  client/src/components/workbookItem/WorkbookItem.tsx
  client/src/pages/Search.tsx
  client/src/pages/mypage/MyPage.tsx
  client/src/pages/mypage/Style.tsx
  client/src/types/search.ts
Labels: 🧩 frontend, 🎨 design

#158 [ETC] Add nginx configuration file on deploy directory
  deploy/nginx.blue.conf
  deploy/nginx.green.conf
Labels: 💻 feat, 🙅 리뷰 X

#148 [FEAT] Workbook Detail API & Refactor
  client/src/api/login.ts
  client/src/api/question.ts
  client/src/api/workbook.ts
  client/src/assets/images/small_logo.png
  client/src/components/common/Logo.tsx
  client/src/components/common/logo/index.tsx
  client/src/components/header/Header.tsx
  client/src/components/modal/create/constants.ts
  client/src/components/modal/create/index.tsx
  client/src/hooks/useArrayText.tsx
  client/src/mocks/data/workbook.ts
  client/src/mocks/handlers/question.ts
  client/src/mocks/handlers/workbook.ts
  client/src/pages/Problem.tsx
  client/src/pages/home/index.tsx
  client/src/pages/login/Login.tsx
  client/src/pages/mypage/index.tsx
  client/src/pages/workbook/Style.tsx
  client/src/pages/workbook/constants.ts
  client/src/pages/workbook/index.tsx
  client/src/pages/workbookCreate/Style.tsx
  client/src/pages/workbookCreate/index.tsx
  client/src/react-query/keys/workbook.ts
  client/src/router/Router.tsx
  client/src/types/question.ts
  client/src/types/workbook.ts
  client/src/utils/constants.ts
Labels: 💻 feat, 🛠 refactor, 🧩 frontend, 🙋 리뷰요청

#151 [DESIGN] 문제집 검색 아이템 디자인 수정 및 검색 상세정보 페이지 구조 설계
  client/src/components/search/NewSearchResultItem/NewSearchResultItem.tsx
  client/src/components/search/NewSearchResultItem/Style.tsx
  client/src/components/search/SearchResultItem/SearchResultItem.tsx
  client/src/components/search/SearchResultItem/Style.tsx
  client/src/images/sample-image.jpeg
  client/src/pages/Search.tsx
  client/src/pages/search/Search.tsx
  client/src/pages/search/Style.tsx
  client/src/pages/search/constants.ts
  client/src/pages/workbookDetail/WorkbookDetail.tsx
  client/src/router/Router.tsx
  client/src/utils/constants.ts
Labels: 🧩 frontend, 🙋 리뷰요청, 🎨 design

#163 [FEAT] Test에 title 추가
  server/prisma/schema.prisma
  server/src/modules/test/TestRepository.ts
  server/src/modules/test/TestService.ts
  server/src/modules/test/domain/Test.ts
  server/src/modules/test/dto/request/CreateTestRequest.ts
  server/src/modules/test/dto/response/TestSimpleResponse.ts
Labels: 💻 feat, ⚙️ backend, 🙅 리뷰 X

#161 [FEAT] 회원가입 api 연동
  client/src/pages/signup/SignUp.tsx
  client/src/utils/constants.ts
Labels: 💻 feat, 🧩 frontend

#162 [FEAT] 이미지 업로더 작성
  server/.env.example
  server/package-lock.json
  server/package.json
  server/src/modules/common/CommonModule.ts
  server/src/modules/common/ImageUploader.ts
Labels: 💻 feat, ⚙️ backend, 🙋 리뷰요청

#166 [REFACTOR] Transaction 도입
  server/src/modules/auth/AuthService.ts
  server/src/modules/question/QuestionRepository.ts
  server/src/modules/question/QuestionService.ts
  server/src/modules/test/TestRepository.ts
  server/src/modules/test/TestService.ts
  server/src/modules/user/UserRepository.ts
  server/src/modules/user/UserService.ts
  server/src/modules/workbook/WorkbookRepository.ts
  server/src/modules/workbook/WorkbookService.ts
Labels: 🛠 refactor, ⚙️ backend, 🙋 리뷰요청

#175 [INIT] Redux 설정 및 login storage 관리
  client/.eslintrc.js
  client/package-lock.json
  client/package.json
  client/src/api/login.ts
  client/src/components/header/Header.tsx
  client/src/components/header/Style.tsx
  client/src/images/default-avatar.jpg
  client/src/index.tsx
  client/src/pages/login/index.tsx
  client/src/redux/hooks.ts
  client/src/redux/login/interface.ts
  client/src/redux/login/selector.ts
  client/src/redux/login/slice.ts
  client/src/redux/store.ts
Labels: 👋 init, 🧩 frontend, 🙋 리뷰요청

#182 [FEAT] 내 문제집, 시험 조회 및 검색
  server/package-lock.json
  server/package.json
  server/prisma/schema.prisma
  server/src/modules/auth/AuthController.ts
  server/src/modules/auth/AuthService.ts
  server/src/modules/common/MailService.ts
  server/src/modules/question/QuestionController.ts
  server/src/modules/test/TestController.ts
  server/src/modules/test/TestRepository.ts
  server/src/modules/test/TestService.ts
  server/src/modules/workbook/WorkbookController.ts
  server/src/modules/workbook/WorkbookRepository.ts
  server/src/modules/workbook/WorkbookService.ts
Labels: 💻 feat, ⚙️ backend, 🙋 리뷰요청

#178 [FEAT] 로그아웃 API 작성
  server/src/modules/auth/AuthController.ts
Labels: 💻 feat, ⚙️ backend, 🙋 리뷰요청

#190 [FEAT] email template URI 변경
  server/src/modules/common/MailService.ts
Labels: 🔨 fix, ⚙️ backend, 🙅 리뷰 X

#176 [FEAT] 이미지 업로더 필요 API에 연계
  server/src/modules/question/QuestionController.ts
  server/src/modules/question/QuestionService.ts
  server/src/modules/question/domain/QuestionImage.ts
  server/src/modules/question/dto/request/CreateQuestionRequest.ts
  server/src/modules/user/UserController.ts
  server/src/modules/user/UserModule.ts
  server/src/modules/user/UserService.ts
  server/src/modules/user/domain/User.ts
Labels: 💻 feat, ⚙️ backend, 🙋 리뷰요청

#196 [REFACTOR] Exam create
  client/src/pages/mypage/index.tsx
  client/src/pages/testCreate/index.tsx
Labels: 💻 feat, 🛠 refactor, 🧩 frontend, 🙋 리뷰요청

#197 [REFACTOR] header
  client/src/components/common/dropdown/Style.tsx
  client/src/components/common/dropdown/index.tsx
  client/src/components/header/Style.tsx
  client/src/components/header/index.tsx
  client/src/components/modal/createQuestion/index.tsx
  client/src/components/modal/searchQuestion/index.tsx
  client/src/router/Router.tsx
Labels: 🛠 refactor, 🧩 frontend, 🙋 리뷰요청, 🎨 design

#199 [DESIGN] 검색페이지 디자인 변경 (이미지삭제)
  client/src/api/search.ts
  client/src/api/workbook.ts
  client/src/components/header/index.tsx
  client/src/components/search/NewSearchResultItem/NewSearchResultItem.tsx
  client/src/components/search/SearchResultItem/Style.tsx
  client/src/components/search/SearchResultItem/index.tsx
  client/src/components/search/SelectSearchType/index.tsx
  client/src/images/sample-question-image.png
  client/src/mocks/handlers/workbook.ts
  client/src/pages/search/Style.tsx
  client/src/pages/search/constants.ts
  client/src/pages/search/index.tsx
  client/src/pages/workbookDetail/Style.ts
  client/src/pages/workbookDetail/WorkbookDetail.tsx
  client/src/pages/workbookDetail/index.tsx
  client/src/redux/search/searchType/interface.ts
  client/src/redux/search/searchType/selector.ts
  client/src/redux/search/searchType/slice.ts
  client/src/redux/store.ts
  client/src/router/Router.tsx
Labels: 🧩 frontend, 🙋 리뷰요청, 🎨 design

#198 [INIT] Public SEO
  client/public/favicon.ico
  client/public/index.html
  client/public/logo180.png
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
Labels: 👋 init

#193 [REFACTOR] Workbook create form
  client/.eslintrc.js
  client/src/components/modal/createQuestion/Style.tsx
  client/src/components/modal/createQuestion/forms/QuestionAnswerForm.tsx
  client/src/components/modal/createQuestion/forms/QuestionEtcForm.tsx
  client/src/components/modal/createQuestion/forms/QuestionInfoForm.tsx
  client/src/components/modal/createQuestion/index.tsx
  client/src/components/solve/contents/index.tsx
  client/src/hooks/useMultistepForm.tsx
  client/src/pages/workBookCreate/index.tsx
  client/src/utils/constants.ts
  server/.eslintrc.js
Labels: 💻 feat, 🛠 refactor, 🧩 frontend, 🙋 리뷰요청

#201 [FEAT] 마이페이지에서나의문제집, 공유받은 문제집 볼수있다.
  client/src/api/workbook.ts
  client/src/components/mypage/Loading.tsx
  client/src/components/mypage/NoSearchResult.tsx
  client/src/components/mypage/Workbook.tsx
  client/src/images/loading.gif
  client/src/mocks/handlers/workbook.ts
  client/src/pages/mypage/index.tsx
  client/src/utils/constants.ts
Labels: 🧩 frontend, 🎨 design

#205 [FIX] CreateQuestion
  client/src/components/modal/createQuestion/index.tsx
Labels: 🔨 fix, 🙅 리뷰 X

#200 [FEAT] 시험지 상세 조회 API 구현
  server/prisma/schema.prisma
  server/src/modules/question/domain/Question.ts
  server/src/modules/test/TestController.ts
  server/src/modules/test/TestRepository.ts
  server/src/modules/test/TestService.ts
  server/src/modules/testPaper/TestPaperController.ts
  server/src/modules/testPaper/TestPaperRepository.ts
  server/src/modules/testPaper/TestPaperService.ts
  server/src/modules/testPaper/domain/TestPaper.ts
  server/src/modules/testPaper/dto/response/TestPaperDetailResponse.ts
  server/src/modules/testPaper/dto/response/TestPaperQuestionSimpleResponse.ts
Labels: 💻 feat, ⚙️ backend, 🙋 리뷰요청, 📑 docs

#215 [REFACTER] Axios
  client/src/api/auth.ts
  client/src/api/index.ts
  client/src/api/login.ts
  client/src/api/question.ts
  client/src/api/search.ts
  client/src/api/test.ts
  client/src/api/workbook.ts
Labels: 💻 feat, 🛠 refactor, 🧩 frontend

#222 [FIX] 유저 모듈 미등록 상황 수정
  server/src/AppModule.ts
Labels: 🔨 fix, ⚙️ backend, 🙅 리뷰 X, 중요도 상🔥

#216 [REFACTOR] CI/CD 코드 구조 개선
  .github/workflows/backend-dev.yml
  .github/workflows/backend-prod.yml
  .github/workflows/front_dev.yml
  .github/workflows/front_prod.yml
  .github/workflows/frontend-dev.yml
  .github/workflows/frontend-prod.yml
  client/.env.example
  client/Dockerfile
  client/package.json
  client/src/pages/workbookCreate/Style.tsx
  client/src/pages/workbookCreate/index.tsx
  deploy/backend/deploy-blue-green.sh
  deploy/backend/docker-compose.blue.yml
  deploy/backend/docker-compose.green.yml
  deploy/backend/nginx.blue.conf
  deploy/backend/nginx.green.conf
  deploy/deploy-blue-green.sh
  deploy/frontend/deploy-blue-green.sh
  deploy/frontend/docker-compose.blue.yml
  deploy/frontend/docker-compose.green.yml
  deploy/frontend/nginx.blue.conf
  deploy/frontend/nginx.green.conf
Labels: 🛠 refactor, 🔨 fix, 🙋 리뷰요청, 중요도 상🔥

#219 [FEAT] Workbook save
  client/src/api/workbook.ts
  client/src/components/search/SearchResultItem/index.tsx
  client/src/pages/workbookDetail/index.tsx
Labels: 💻 feat, 🧩 frontend, 🙋 리뷰요청

#204 [REFACTOR] 로그인 관련 기능 리팩토링
  client/src/api/auth.ts
  client/src/components/login/LoginModal.tsx
  client/src/components/login/ToggleVisible.tsx
  client/src/pages/FindId/FindId.tsx
  client/src/pages/FindId/Style.tsx
  client/src/pages/emailAuth/index.tsx
  client/src/pages/findPw/FindPw.tsx
  client/src/pages/findPw/Style.tsx
  client/src/pages/login/index.tsx
  client/src/pages/passwordAuth/index.tsx
  client/src/pages/signup/SignUp.test.tsx
  client/src/pages/signup/SignUp.tsx
  client/src/pages/signup/Style.tsx
  client/src/pages/signup/constants.ts
  client/src/pages/signup/index.tsx
  client/src/router/Router.tsx
  client/src/types/auth.ts
  client/src/utils/constants.ts
Labels: 🛠 refactor, 🧩 frontend

#213 [FEAT] 시험지 객관식 문제 자동채점 API 구현
  server/prisma/schema.prisma
  server/src/modules/testPaper/TestPaperController.ts
  server/src/modules/testPaper/TestPaperRepository.ts
  server/src/modules/testPaper/TestPaperService.ts
  server/src/modules/testPaper/domain/TestPaper.ts
  server/src/modules/testPaper/domain/TestPaperQuestion.ts
  server/src/modules/testPaper/dto/request/GradeTestPaperQuestionRequest.ts
  server/src/modules/testPaper/dto/request/GradeTestPaperRequest.ts
  server/src/modules/testPaper/dto/request/MarkTestPaperQuestionRequest.ts
  server/src/modules/testPaper/dto/request/MarkTestPaperRequest.ts
  server/src/modules/testPaper/dto/response/TestPaperDetailResponse.ts
  server/src/modules/testPaper/dto/response/TestPaperGradedResponse.ts
  server/src/modules/testPaper/dto/response/TestPaperQuestionDetailResponse.ts
  server/src/modules/testPaper/dto/response/TestPaperSimpleResponse.ts
  server/src/modules/testPaper/enum/TestPaperQuestionState.ts
  server/src/modules/testPaper/enum/TestPaperState.ts
Labels: 💻 feat, ⚙️ backend, 🙋 리뷰요청

#221 [REFACTOR] Home
  client/src/components/dashboard/index.tsx
  client/src/pages/home/index.tsx
  client/src/pages/mypage/constants.ts
  client/src/pages/mypage/index.tsx
  client/src/utils/constants.ts
Labels: 🛠 refactor, 🧩 frontend, 🙋 리뷰요청

#228 [FIX] CI/CD 수정
  .github/workflows/backend-prod.yml
  .github/workflows/frontend-dev.yml
  deploy/backend/deploy-blue-green.sh
  deploy/backend/nginx.blue.conf
  deploy/backend/nginx.green.conf
  deploy/frontend/deploy-blue-green.sh
  deploy/frontend/nginx.blue.conf
  deploy/frontend/nginx.green.conf
Labels: 🔨 fix, 🙅 리뷰 X, 중요도 상🔥

#223 [FEAT] TestPaper Grade API
  client/.eslintrc.js
  client/src/api/test.ts
  client/src/api/testpaper.ts
  client/src/components/solve/contents/Style.tsx
  client/src/components/solve/contents/contants.ts
  client/src/components/solve/contents/index.tsx
  client/src/components/solve/header/Style.tsx
  client/src/components/solve/header/index.tsx
  client/src/components/solve/index.tsx
  client/src/mocks/data/test.ts
  client/src/mocks/data/workbook.ts
  client/src/mocks/handlers/test.ts
  client/src/mocks/handlers/workbook.ts
  client/src/pages/test/index.tsx
  client/src/pages/testCreate/index.tsx
  client/src/pages/workbook/index.tsx
  client/src/redux/solve/interface.ts
  client/src/redux/solve/slice.ts
  client/src/types/question.ts
  client/src/types/test.ts
  client/src/utils/constants.ts
Labels: 💻 feat, 🧩 frontend, 🙋 리뷰요청

#224 [REFACTOR] Workbook create image form
  client/src/components/modal/createQuestion/Style.tsx
  client/src/components/modal/createQuestion/constants.ts
  client/src/components/modal/createQuestion/forms/QuestionInfoForm.tsx
  client/src/components/modal/createQuestion/index.tsx
  client/src/mocks/handlers/question.ts
  client/src/types/question.ts
Labels: 💻 feat, 🛠 refactor, 🧩 frontend, 🙋 리뷰요청

#230 [FIX] CI/CD 파이프라인 동작하지 않는 오류 수정
  .github/workflows/frontend-dev.yml
Labels: 🔨 fix, 🙅 리뷰 X, 중요도 중💡

#231 fix:confict
  client/src/components/solve/contents/index.tsx
Labels: 🛠 refactor, 🧩 frontend, 🙅 리뷰 X

#225 [FEAT] 마이페이지에서 나의시험과 나의시험지를 확인할 수 있다.
  client/src/api/test.ts
  client/src/api/testpaper.ts
  client/src/components/common/searchResultContainer/Style.tsx
  client/src/components/common/searchResultContainer/index.tsx
  client/src/components/common/utils/Error.tsx
  client/src/components/common/utils/Loading.tsx
  client/src/components/mypage/Loading.tsx
  client/src/components/mypage/NoSearchResult.tsx
  client/src/components/mypage/Workbook.tsx
  client/src/components/mypage/test/Style.tsx
  client/src/components/mypage/test/index.tsx
  client/src/components/mypage/testPaper/Style.tsx
  client/src/components/mypage/testPaper/index.tsx
  client/src/components/mypage/workbook/Style.tsx
  client/src/components/mypage/workbook/index.tsx
  client/src/components/search/SearchResultItem/Style.tsx
  client/src/components/search/SearchResultItem/index.tsx
  client/src/components/search/TestSearchResultItem/QuestionRangeWorkbook/Style.ts
  client/src/components/search/TestSearchResultItem/QuestionRangeWorkbook/index.tsx
  client/src/components/search/TestSearchResultItem/index/Style.ts
  client/src/components/search/TestSearchResultItem/index/index.tsx
  client/src/mocks/data/myTest.ts
  client/src/mocks/handlers/test.ts
  client/src/pages/mypage/Style.tsx
  client/src/pages/mypage/constants.ts
  client/src/pages/mypage/index.tsx
  client/src/styles/theme.ts
  client/src/types/test.ts
  client/src/types/workbook.ts
Labels: 💻 feat, 🧩 frontend, 🎨 design

#227 [TEST] Auth 도메인 테스트 코드 작성
  .gitignore
  server/package.json
  server/src/decorators/ApiResponseDecorator.ts
  server/src/modules/auth/AuthController.ts
  server/src/modules/auth/AuthService.ts
  server/src/modules/auth/dto/request/ResetTokenRequest.ts
  server/src/modules/auth/strategies/JwtStrategy.ts
  server/src/modules/question/QuestionController.ts
  server/src/modules/question/dto/response/QuestionDetailResponse.ts
  server/src/modules/question/dto/response/QuestionSimpleResponse.ts
  server/src/modules/test/TestController.ts
  server/src/modules/test/domain/WorkbookTest.ts
  server/src/modules/user/domain/BasicUser.ts
  server/src/modules/workbook/WorkbookController.ts
  server/src/modules/workbook/domain/WorkbookQuestion.ts
  server/src/modules/workbook/dto/response/WorkbookQuestionSimpleResponse.ts
  server/test/MockInstance.ts
  server/test/auth/AuthController.spec.ts
  server/test/auth/AuthService.spec.ts
Labels: ⚙️ backend, 🔎 test, 🙋 리뷰요청, 중요도 중💡

#229 [FEAT] 시험지 상태 별 리스트 / 상세 조회 API 구현
  server/src/modules/testPaper/TestPaperController.ts
  server/src/modules/testPaper/TestPaperRepository.ts
  server/src/modules/testPaper/TestPaperService.ts
  server/src/modules/testPaper/domain/TestPaperQuestion.ts
  server/src/modules/testPaper/dto/response/ReviewNoteQuestionResponse.ts
  server/src/modules/testPaper/dto/response/ReviewNoteResponse.ts
  server/src/modules/testPaper/dto/response/TestPaperQuestionDetailResponse.ts
Labels: 💻 feat, ⚙️ backend, 🙋 리뷰요청

#237 [HOTFIX] 나의 시험지 생성 관련 리다이렉트 오류 수정
  client/README.md
  client/src/pages/mypage/index.tsx
Labels: 🙅 리뷰 X

#241 [FIX] 문제 생성 시 응답 객체 수정
  server/src/modules/question/dto/response/CreateQuestionResponse.ts
Labels: 🔨 fix, ⚙️ backend, 🙅 리뷰 X

#244 [FIX] 잘못 작성된 컴포넌트 삭제
  client/src/components/mypage/Workbook.tsx
Labels: 🔨 fix, 🧩 frontend, 🙅 리뷰 X, 중요도 상🔥

#245 [FIX] 재완님 요청사항 수정
  server/src/modules/question/dto/response/GetQuestionsResponse.ts
  server/src/modules/test/TestService.ts
  server/src/modules/test/dto/request/CreateTestRequest.ts
  server/src/modules/workbook/WorkbookController.ts
  server/src/modules/workbook/WorkbookService.ts
  server/src/modules/workbook/dto/request/SolveWorkbookQuestionRequest.ts
Labels: 🛠 refactor, 🔨 fix, 🙅 리뷰 X

#250 [HOTFIX] 채점 api 버그 수정
  server/src/modules/common/PageRequest.ts
  server/src/modules/testPaper/TestPaperController.ts
  server/src/modules/testPaper/domain/TestPaperQuestion.ts
  server/src/modules/testPaper/dto/request/GradeTestPaperQuestionRequest.ts
  server/src/modules/testPaper/dto/request/MarkTestPaperQuestionRequest.ts
Labels: 🔨 fix, ⚙️ backend, 🙅 리뷰 X, 중요도 상🔥

#252 [FIX] 유저 프로필 이미지 업로드 오류 수정
  server/src/modules/common/ImageUploader.ts
  server/src/modules/user/UserController.ts
Labels: 🔨 fix, ⚙️ backend, 🙅 리뷰 X, 중요도 상🔥

#256 [FIX] 리다이렉트 주소 수정
  client/src/components/mypage/workbook/index.tsx
  client/src/components/search/SearchResultItem/index.tsx
Labels: 🔨 fix, 🙅 리뷰 X

#243 [REFACTOR] 문제 생성 API
  client/src/components/modal/createQuestion/forms/QuestionAnswerForm.tsx
  client/src/components/modal/createQuestion/index.tsx
  client/src/pages/workbookCreate/index.tsx
Labels: 💻 feat, 🛠 refactor, 🧩 frontend, 🙋 리뷰요청

#249 [FEAT] 좋아요 / 좋아요 취소 API 작성
  server/src/modules/question/QuestionController.ts
  server/src/modules/question/QuestionRepository.ts
  server/src/modules/question/QuestionService.ts
  server/src/modules/question/domain/QuestionLike.ts
  server/src/modules/question/dto/response/GetQuestionsResponse.ts
  server/src/modules/question/dto/response/LikeQuestionResponse.ts
  server/src/modules/workbook/WorkbookController.ts
  server/src/modules/workbook/WorkbookRepository.ts
  server/src/modules/workbook/WorkbookService.ts
  server/src/modules/workbook/domain/WorkbookLike.ts
  server/src/modules/workbook/dto/response/LikeWorkbookResponse.ts
  server/src/modules/workbook/dto/response/WorkbookSearchResponse.ts
Labels: 💻 feat, ⚙️ backend, 🙋 리뷰요청, 중요도 중💡

#258 12/14 오전 작업사항 반영
  client/src/api/testpaper.ts
  client/src/api/workbook.ts
  client/src/components/modal/createQuestion/forms/QuestionAnswerForm.tsx
  client/src/components/modal/createQuestion/index.tsx
  client/src/components/modal/searchWorkbook/index.tsx
  client/src/components/solve/contents/index.tsx
  client/src/components/solve/header/index.tsx
  client/src/components/solve/index.tsx
  client/src/pages/test/index.tsx
  client/src/pages/testCreate/index.tsx
  client/src/pages/workbook/index.tsx
  client/src/pages/workbookCreate/index.tsx
  client/src/react-query/queryClient.ts
  client/src/redux/solve/interface.ts
  client/src/redux/solve/slice.ts
  client/src/types/question.ts
  client/src/types/test.ts
  client/src/types/workbook.ts
  server/src/modules/question/QuestionController.ts
  server/src/modules/question/QuestionRepository.ts
  server/src/modules/question/QuestionService.ts
  server/src/modules/question/domain/QuestionLike.ts
  server/src/modules/question/dto/response/GetQuestionsResponse.ts
  server/src/modules/question/dto/response/LikeQuestionResponse.ts
  server/src/modules/workbook/WorkbookController.ts
  server/src/modules/workbook/WorkbookRepository.ts
  server/src/modules/workbook/WorkbookService.ts
  server/src/modules/workbook/domain/WorkbookLike.ts
  server/src/modules/workbook/dto/response/LikeWorkbookResponse.ts
  server/src/modules/workbook/dto/response/WorkbookSearchResponse.ts
Labels: 🙅 리뷰 X

#251 [FEAT] 마이페이지 - 프로필 변경 API
  client/src/api/user.ts
  client/src/components/header/index.tsx
  client/src/pages/mypage/Style.tsx
  client/src/pages/mypage/index.tsx
  client/src/redux/login/interface.ts
  client/src/redux/login/slice.ts
  client/src/types/user.ts
  client/src/utils/constants.ts
Labels: 💻 feat, 🧩 frontend, 🙋 리뷰요청

#266 [FIX] GET /questions 에 hashtag 추가
  server/src/modules/question/dto/response/GetQuestionsResponse.ts
Labels: 🛠 refactor, 🔨 fix, ⚙️ backend, 🙅 리뷰 X, 중요도 하🐪

#264 [FEAT] 메인페이지 API 작업
  server/src/modules/question/QuestionController.ts
  server/src/modules/user/UserController.ts
  server/src/modules/user/UserRepository.ts
  server/src/modules/user/UserService.ts
  server/src/modules/user/dto/response/MyDataResponse.ts
Labels: 💻 feat, ⚙️ backend, 🙋 리뷰요청, 중요도 중💡

#255 [REFACTOR] 문제집 상세보기 페이지 리뉴얼 및 좋아요기능 연동
  client/src/api/like.ts
  client/src/api/workbook.ts
  client/src/components/workbookDetail/Style.ts
  client/src/components/workbookDetail/index.tsx
  client/src/pages/search/index.tsx
  client/src/pages/workbookDetail/Style.ts
  client/src/pages/workbookDetail/index.tsx
  client/src/types/question.ts
  client/src/utils/constants.ts
Labels: 💻 feat, 🛠 refactor, 🧩 frontend

#259 [FEAT] init page 추가
  client/src/pages/home/index.tsx
  client/src/pages/initpage/Style.ts
  client/src/pages/initpage/index.tsx
  client/src/router/Router.tsx
Labels: 💻 feat, 🧩 frontend, 🎨 design

#267 [REFACTOR] Search question
  client/src/components/modal/searchQuestion/index.tsx
  client/src/components/solve/contents/Style.tsx
  client/src/components/solve/contents/index.tsx
  client/src/types/question.ts
Labels: 💻 feat, 🛠 refactor, 🧩 frontend, 🙋 리뷰요청

#268 [FEAT] 메인 - user info API 연동
  client/package-lock.json
  client/package.json
  client/src/api/login.ts
  client/src/api/user.ts
  client/src/components/chart/Chart.tsx
  client/src/components/dashboard/index.tsx
  client/src/components/header/Style.tsx
  client/src/components/header/index.tsx
  client/src/hooks/useUserData.tsx
  client/src/pages/home/index.tsx
  client/src/pages/login/index.tsx
  client/src/pages/mypage/index.tsx
  client/src/pages/workbookDetail/index.tsx
  client/src/react-query/keys/user.ts
  client/src/redux/login/selector.ts
  client/src/redux/store.ts
  client/src/redux/user/interface.ts
  client/src/redux/user/selector.ts
  client/src/redux/user/slice.ts
  client/src/styles/theme.ts
  client/src/types/question.ts
  client/src/types/user.ts
  client/src/types/workbook.ts
Labels: 💻 feat, 🛠 refactor, 🧩 frontend, 🙋 리뷰요청

#270 [FEAT/FIX] 마이페이지 - 나의시험지 확인 및 버그수정
  client/src/api/testpaper.ts
  client/src/components/mypage/testPaper/Style.tsx
  client/src/components/mypage/testPaper/index.tsx
  client/src/components/mypage/workbook/index.tsx
  client/src/components/search/SearchResultItem/index.tsx
  client/src/components/search/TestPaperSearchResultItem/index.tsx
  client/src/components/search/TestSearchResultItem/index/index.tsx
  client/src/pages/mypage/index.tsx
  client/src/types/search.ts
Labels: 💻 feat, 🧩 frontend, 🎨 design

#271 develop 브랜치 작업사항 적용
  client/package-lock.json
  client/package.json
  client/src/api/like.ts
  client/src/api/login.ts
  client/src/api/testpaper.ts
  client/src/api/user.ts
  client/src/api/workbook.ts
  client/src/components/chart/Chart.tsx
  client/src/components/common/Toggle.tsx
  client/src/components/dashboard/index.tsx
  client/src/components/header/Style.tsx
  client/src/components/header/index.tsx
  client/src/components/modal/searchQuestion/Style.tsx
  client/src/components/modal/searchQuestion/index.tsx
  client/src/components/mypage/testPaper/Style.tsx
  client/src/components/mypage/testPaper/index.tsx
  client/src/components/mypage/workbook/index.tsx
  client/src/components/search/SearchResultItem/index.tsx
  client/src/components/search/TestPaperSearchResultItem/index.tsx
  client/src/components/search/TestSearchResultItem/index/index.tsx
  client/src/components/solve/contents/Style.tsx
  client/src/components/solve/contents/index.tsx
  client/src/components/workbookDetail/Style.ts
  client/src/components/workbookDetail/index.tsx
  client/src/hooks/useUserData.tsx
  client/src/pages/home/index.tsx
  client/src/pages/initpage/Style.ts
  client/src/pages/initpage/index.tsx
  client/src/pages/login/index.tsx
  client/src/pages/mypage/Style.tsx
  client/src/pages/mypage/index.tsx
  client/src/pages/search/index.tsx
  client/src/pages/workbookCreate/Style.tsx
  client/src/pages/workbookCreate/index.tsx
  client/src/pages/workbookDetail/Style.ts
  client/src/pages/workbookDetail/index.tsx
  client/src/react-query/keys/user.ts
  client/src/redux/login/interface.ts
  client/src/redux/login/selector.ts
  client/src/redux/store.ts
  client/src/redux/user/interface.ts
  client/src/redux/user/selector.ts
  client/src/redux/user/slice.ts
  client/src/router/Router.tsx
  client/src/styles/theme.ts
  client/src/types/question.ts
  client/src/types/search.ts
  client/src/types/user.ts
  client/src/types/workbook.ts
  client/src/utils/constants.ts
  deploy/backend/deploy-blue-green.sh
  server/src/modules/question/QuestionController.ts
  server/src/modules/question/dto/response/GetQuestionsResponse.ts
  server/src/modules/test/TestService.ts
  server/src/modules/user/UserController.ts
  server/src/modules/user/UserRepository.ts
  server/src/modules/user/UserService.ts
  server/src/modules/user/dto/response/MyDataResponse.ts
Labels: 🙅 리뷰 X

#272 [REFACTOR] Workbook link
  client/src/components/modal/createQuestion/forms/QuestionAnswerForm.tsx
  client/src/components/modal/createQuestion/forms/QuestionInfoForm.tsx
  client/src/components/search/TestSearchResultItem/index/index.tsx
  client/src/components/solve/contents/index.tsx
Labels: 🛠 refactor, 🧩 frontend, 🙅 리뷰 X

#277 [DOCS] README 업데이트
  README.md
  client/src/components/modal/createQuestion/forms/QuestionAnswerForm.tsx
  client/src/components/modal/createQuestion/forms/QuestionInfoForm.tsx
  client/src/components/search/TestSearchResultItem/index/index.tsx
  client/src/components/solve/contents/index.tsx
Labels: 🙅 리뷰 X, 📑 docs

#273 [REFACTOR] 로그인 - 디자인
  client/.env.development
  client/.env.production
  client/src/api/auth.ts
  client/src/components/login/LoginModal.tsx
  client/src/pages/findPw/FindPw.tsx
  client/src/pages/login/Style.tsx
  client/src/pages/login/constants.ts
  client/src/pages/login/index.tsx
  client/src/pages/signup/Style.tsx
  client/src/pages/signup/index.tsx
Labels: 🧩 frontend, 🎨 design

#274 [REFACTOR] Question naming
  client/src/components/modal/createQuestion/index.tsx
  client/src/components/modal/searchQuestion/Style.tsx
  client/src/components/modal/searchQuestion/index.tsx
  client/src/components/modal/searchWorkbook/Style.tsx
  client/src/components/modal/searchWorkbook/index.tsx
  client/src/pages/workbookCreate/Style.tsx
  client/src/pages/workbookCreate/index.tsx
  client/src/styles/questionList.tsx
Labels: 🛠 refactor, 🧩 frontend, 🙋 리뷰요청

#284 [REFACTOR] Question_add
  client/src/api/workbook.ts
  client/src/components/modal/searchQuestion/index.tsx
  client/src/pages/workbookCreate/index.tsx
Labels: 🛠 refactor, 🧩 frontend

#287 [HOTFIX] 나의 문제집 문제 수가 undefined로 출력되던 버그 수정
  client/src/components/mypage/workbook/index.tsx
  client/src/types/search.ts
Labels: 🔨 fix

#288 버그 수정내역 머지
  client/src/components/mypage/workbook/index.tsx
  client/src/types/search.ts
Labels: 🙅 리뷰 X
